---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: karmada-operator-controller-manager
  name: karmada-operator-controller-manager-service
  namespace: karmada-operator-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: karmada-operator-controller-manager